language: scala
scala:
  - 2.12.10
  - 2.13.1

git:
  depth: false # Avoid sbt-dynver not seeing the tag

env:
  - TRAVIS_JDK=8
  - TRAVIS_JDK=11

before_install: curl -Ls https://git.io/jabba | bash && . ~/.jabba/jabba.sh
install: jabba install "adopt@~1.$TRAVIS_JDK.0-0" && jabba use "$_" && java -Xmx32m -version

script:
  - ./scripts/test-code.sh
  - ./scripts/validate-code.sh
  - ./scripts/validate-docs.sh

jobs:
  allow_failures:
    - env: TRAVIS_JDK=13
  include:
    - scala: 2.13.1
      env: TRAVIS_JDK=13
      script: SBT_VERSION=1.3.4 ./scripts/test-code.sh

cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.jabba/jdk"
  - "$HOME/.coursier"
  - "$HOME/.sbt"

before_cache:
  - rm -rf $HOME/.ivy2/cache/com.typesafe.play/twirl*
  - rm -rf $HOME/.ivy2/cache/scala_*/sbt_*/com.typesafe.sbt/sbt-twirl
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt  -name "*.lock"               -delete

notifications:
  webhooks:
    urls: https://webhooks.gitter.im/e/d2c8a242a2615f659595
    on_success: always
    on_failure: always
  slack:
    secure: lrBEBp00Fwr3T72GXK+eOaQVNy34QT+OBcJanr/WCVoD3kgt+L5hkEZ3iS9B7pDd26vMBcUGBb5kM8Z5QGo48gvbLUFgRtaTU00EBoTXbUPDIqlaMkuxdF+TN7GgS7yZKnKIInj54e7o1QaJ4R/I/Atw81kUJr0PNzMU0hfg6VU=
